# Generated by Django 4.1.7 on 2023-04-21 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Início do contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_day',
            field=models.SmallIntegerField(choices=[(1, 'Dia 1'), (2, 'Dia 2'), (3, 'Dia 3'), (4, 'Dia 4'), (5, 'Dia 5'), (6, 'Dia 6'), (7, 'Dia 7'), (8, 'Dia 8'), (9, 'Dia 9'), (10, 'Dia 10'), (11, 'Dia 11'), (12, 'Dia 12'), (13, 'Dia 13'), (14, 'Dia 14'), (15, 'Dia 15'), (16, 'Dia 16'), (17, 'Dia 17'), (18, 'Dia 18'), (19, 'Dia 19'), (20, 'Dia 20'), (21, 'Dia 21'), (22, 'Dia 22'), (23, 'Dia 23'), (24, 'Dia 24'), (25, 'Dia 25'), (26, 'Dia 26'), (27, 'Dia 27'), (28, 'Dia 28'), (29, 'Dia 29'), (30, 'Dia 30')], default=1, verbose_name='Dia de pagamento'),
        ),
    ]
