# Generated by Django 4.1.7 on 2023-04-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_start_at_alter_contract_payment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_at',
            field=models.DateField(auto_now_add=True, verbose_name='Início do contrato'),
        ),
    ]
