# Generated by Django 4.1.7 on 2023-04-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_start_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-start_at',), 'verbose_name': 'Contrato'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='contribution',
            field=models.FloatField(verbose_name='Investimento inicial'),
        ),
    ]
