# Generated by Django 4.1.7 on 2023-04-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_options_alter_contract_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_at',
            field=models.DateField(verbose_name='Início do contrato'),
        ),
    ]
