# Generated by Django 4.1.7 on 2023-03-24 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.FloatField()),
                ('duration', models.IntegerField(verbose_name='Duração em meses')),
                ('payment', models.CharField(choices=[(1, '01'), (5, '05'), (10, '10'), (15, '15'), (20, '20'), (25, '25')], default=1, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField(verbose_name='Valor do Contrato')),
                ('receipt', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('order', models.CharField(max_length=5, verbose_name='Sequencial')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
            ],
        ),
    ]
