# Generated by Django 4.1.7 on 2023-03-24 13:01

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('payment_date', models.DateField()),
                ('receipt', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor pago')),
                ('order', models.SmallIntegerField(verbose_name='Sequencial')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Dividendo',
                'verbose_name_plural': 'Dividendos',
                'ordering': ('-payment_date',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
