# Generated by Django 4.1.7 on 2023-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='receipt',
            field=models.FileField(upload_to='recibos/%Y/%m/%d/'),
        ),
    ]
