# Generated by Django 4.1.7 on 2023-04-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0002_alter_dividend_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='receipt',
            field=models.FileField(upload_to='recibos/%Y/%m/%d/', verbose_name='Comprovante de pagamento'),
        ),
    ]
